### ISSUE TITLE
Install broken on Arch

### ISSUE THREAD

**Issue by paulie-g** [drmargarido/d-tracker#1]
Arch install breaks because of an install-time dependency on busted. Busted fails to install on Arch currently because --no-manifest appears to be an invalid argument to luarocks, ie "luareasons"

**Comment by drmargarido** [comment]
Thanks for your report.

I removed the check step of the PKGBUILD so now busted is not a dependency anymore.

**Comment by paulie-g** [comment]
That makes sense. In general, if you wanted to use it to run tests post-build, you'd want to include it as a formal dependency in the PKGBUILD. It would still be broken in this case since its package in AUR is borked, but it'd at least be formally correct ;)

Looks nice, btw, and comes in at a very lightweight 4.5MB unique set size.
