### ISSUE TITLE
CLI add-task: parsing args error

### ISSUE THREAD

**Issue by ubermanu** [drmargarido/d-tracker#10]
Version: **1.52.r1.g99e6ed1-1** (from AUR)

I cannot add a task from cli if its name or project contains spaces

    $ d-tracker-cli add-task "my task with spaces" "my project name" 
    Usage: d-tracker-cli add-task [-h] <description> <project>

    Error: too many arguments

**Comment by drmargarido** [comment]
Hello, that looks weird, what shell are you using?
Have you tried using `'` as a string delimiter instead of `"`?

Edit: Was able to reproduce it now, will check what is happening.

**Comment by drmargarido** [comment]
Fixed on this commit https://github.com/drmargarido/d-tracker/commit/44a2e6eae6b197a686721546afd9eaddc8c7502c, will be deployed in the next release
